### ISSUE TITLE
[Solved] 如何进行本地开发 或者 考虑增加contribution guide？

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#105]
请教一个本地开发的问题，和 npm link 相关；
以 html field 这个需求为例，或者是我想在做实际项目的同时，来 debug 学习 ams

想反馈下：是否可以增加一些 本地开发或者 contribution guide，方便在本地运行

背景：
我的项目：xxx-admin xxx管理后台（在这个项目中用到了 ams）
然后 git clone 了 ams，在 ams 的目录 
1. yarn link
2. npm install 【请问这里是不要借助npx lerna 来做一些其他初始化的事情】

然后在 xxx-admin 的目录下：
1. yarn link @ams-team/ams
2. yarn serve

然后会有报错，显示 link 的 ams 项目中有很多依赖没有安装，想请教下，ams 项目如何进行初始化进行本地开发，感谢

```bash
 error  in /Users/lambert/Documents/GitHub/ams/src/blocks/carousel/carousel.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-import'
Require stack:
- xxx-admin/noop.js

(@/Users/lambert/Documents/GitHub/ams/.postcssrc.js)
    at load (x x x/node_modules/postcss-load-config/src/plugins.js:28:11)
    at xxx-admin/node_modules/postcss-load-config/src/plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (xxx-admin/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (xxx-admin/node_modules/postcss-load-config/src/index.js:33:14)
    at xxx-admin/node_modules/postcss-load-config/src/index.js:94:14

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!/Users/lambert/Documents/GitHub/ams/src/blocks/carousel/carousel.vue?vue&type=style&index=0&lang=scss& 4:14-682 14:3-18:5 15:22-690
 @ /Users/lambert/Documents/GitHub/ams/src/blocks/carousel/carousel.vue?vue&type=style&index=0&lang=scss&
 @ /Users/lambert/Documents/GitHub/ams/src/blocks/carousel/carousel.vue
 @ /Users/lambert/Documents/GitHub/ams/src/blocks/carousel/index.js
 @ /Users/lambert/Documents/GitHub/ams/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.10.20.102:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by ly525** [comment]
已经解决：

### 1. ams 项目
1. `npm install`
2. `yarn link`

### 2. xxx-admin 项目
```js
yarn link @ams-team/ams
// 怀疑和https://github.com/vipshop/ams/blob/master/.postcssrc.js 有关，但具体原因不详
yarn add postcss-import postcss-url
yarn serve
```
