### ISSUE TITLE
win7下cli初始化ams项目失败

### ISSUE THREAD

**Issue by qq974837057** [vipshop/ams#11]
$ ams create hello-ams
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'D:\Mydata\Desktop\ams-project\index-create'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by w3cmark** [comment]
请尝试使用 `ams-create hello-ams` 替代（ams init、ams field、 ams block等同理）
同时手动安装依赖，`cd hello-ams && npm i`

**Comment by qq974837057** [comment]
$ ams-create hello-ams
bash: ams-create: command not found
同样失败了 求解

**Comment by cubemoon** [comment]
win10下同样问题，求解 @w3cmark

**Comment by shamedlulu** [comment]
win11+1
